### PR TITLE
Adapt to Android gradle plugin 1.5.0

### LINKED ISSUE #74: Problem with missing ddmlib method
* What went wrong:
    Execution failed for task ':app:spoonProductionDebugAndroidTest'.
    > com.android.ddmlib.IDevice.installPackage(Ljava/lang/String;Z[Ljava/lang/String;)Ljava/lang/String;

I'm not really sure what's the problem, but I will leave it here and investigate more in future

### PR DESCRIPTION
**Pull request by roman-mazur**
This fixes #74, #85.
Now tests can be run. 
But I'm personally still facing with https://github.com/square/spoon/issues/302

### CODE REVIEW

**Comment by roman-mazur** [comment]
Playing with sdk/emulator configuration on travis...

**Comment by jfmoy** [comment]
Continuous Integration server should be updated as Build Tools are out of date. You guys could use the sdk-manager-plugin from Jake Wharton to perform automatic updates.

**Comment by x2on** [comment]
Hi @roman-mazur 
i created a bug report on the google tools: https://code.google.com/p/android/issues/detail?id=195998

**Comment by roman-mazur** [comment]
Thanks @x2on. I appreciate this.

**Comment by x2on** [comment]
Hi @roman-mazur ,

i found a workaround for the gradle-1.5.0 plugin:
https://github.com/x2on/gradle-spoon-plugin/commit/724bf4993d6eca48276d393771df7e73b5d68c9b

Perhaps its also helpfull for your plugin.

**Comment by x2on** [comment]
Now i found the real root cause.

For gradle plugin 1.5.0 you could use this workaround in your build.gradle:
```groovy
// Workaround for Multidex bug in gradle-android-plugin
// Replace Multidex dependency with some dummy dependency to avoid dex problems
// @see https://code.google.com/p/android/issues/detail?id=194609
project.getConfigurations().all { config ->
    if (config.name.contains("AndroidTest")) {
        config.resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            if (details.requested.name == "multidex") {
                details.useTarget("de.felixschulze.teamcity:teamcity-status-message-helper:1.2")
            }
        }
    }
}
```

**Comment by Nilzor** [comment]
a) when is this PR going to get merged and released?
b) Anyone tested with `gradle 2.0.0-alpha2`?
c) @x2on : I could not get that workaround to work. Can you tell me a bit about what the code is supposed to do and why it would solve the problem? Also are there any side effects?

**Comment by x2on** [comment]
@Nilzor for me the problem was when using multidex. during a dependency bug in the gradle-android-plugin-1.5.0 the test app didn't start. With exchanging the multiple dependency with some dummy jar it works here.

**Comment by Nilzor** [comment]
Ok got it. Anyway I'm trying to build this branch myself instead. First I got 

>Cannot find spoon-runner in dependencies

when executing `spoon` on my app with my own build of this branch. So I added  `androidTestCompile 'com.squareup.spoon:spoon-runner:1.2.1'` but then it complained about `gson` version conflict so I changed it to

    androidTestCompile ('com.squareup.spoon:spoon-runner:1.2.1') {
        exclude module: 'gson'
    }

..but now I'm getting

```com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK NOTICE
	File1: C:\Users\nilzo.DESKTOP-DS214RV\.gradle\caches\modules-2\files-2.1\com.android.tools.ddms\ddmlib\24.5.0\d45670b5511da60d2939a1eece4c7c4407fee95b\ddmlib-24.5.0.jar
	File2: C:\Users\nilzo.DESKTOP-DS214RV\.gradle\caches\modules-2\files-2.1\com.android.tools\common\24.5.0\55436737b893bac95c978b184dd35c76002d2eef\common-24.5.0.jar
	File3: C:\Users\nilzo.DESKTOP-DS214RV\.gradle\caches\modules-2\files-2.1\com.android.tools\annotations\24.5.0\7f2bcdf40b008f15481324327b7f9e377b0b1697\annotations-24.5.0.jar```

Any tips on getting past this? Our whole CI system is currently down... Starting to regret depending on spoon.

**Comment by roman-mazur** [comment]
Still cannot get this working on API 23 emulator on Travis (even with spoon runner 1.3.0 which should grant external storage permissions). But I will merge this. If somebody can test a new snapshot and tell if it works, I will release to Maven Central.

**Comment by roman-mazur** [comment]
See 1.0.4-SNAPSHOT: https://oss.sonatype.org/content/repositories/snapshots/com/stanfy/spoon/spoon-gradle-plugin/1.0.4-SNAPSHOT/

**Comment by ming13** [comment]
Just tried `1.0.4-SNAPSHOT`. It works, but I had to specify `spoon {adbTimeout = 30}`, otherwise Spoon quits immediately.

**Comment by roman-mazur** [comment]
1.0.4 is promoted to Maven Central

**Pull request merged**
