### PR TITLE
Sharding support for spoon-gradle-plugin

### PR DESCRIPTION
**Pull request by jainsahab**
adding support to use spoon-runner's inbuilt `shard` option for multiple devices. It will automatically shard across all devices, and merge the results.

### CODE REVIEW

**Comment by roman-mazur** [comment]
Thanks @jainsahab 
How does this adjust with https://github.com/stanfy/spoon-gradle-plugin#test-sharding ?

**Comment by jainsahab** [comment]
thanks @roman-mazur for the quick response. This change will not impact sharding behaviour that is currently present in spoon-runner. After this change, spoon-gradle-plugin will just pass-over the arguments to runner without any intelligence. Spoon-runner will behave same as it used to behave while passing arguments using its java command - `java -jar spoon-runner.jar --shard --e numShards=2 --e shardIndex=0`

FYI, I have also verified the behavior of spoon-runner when passing `--shard` `numShards` and `shardIndex`, in which case `--shard` takes the precendence and number of shards will be calculated based on number of available devices and not `numShards`.

**Comment by pavanagarwal** [comment]
when would this inbuilt "shard" option available in a release?

**Comment by roman-mazur** [comment]
I need to take a look at compatibility with the latest Android Gradle plugin. Probably next week.

**Pull request merged**
