### PR TITLE
Added support to provide device Id on runtime.

### PR DESCRIPTION
**Pull request by jainsahab**
Added support to provide device Id on runtime. so that user can run test for different variants on different device in Parallel way.
Let me know, if you have any thoughts on this.

### CODE REVIEW

**Comment by roman-mazur** [comment]
Device IDs can be specified using the `spoon` extension in an application `build.gradle`.
```
spoon {
  devices = ['333236E9AE5800EC']
}
```
And in your build.gradle file you can use a project property to provide values via the command line.
It should work for you too.

**Comment by jainsahab** [comment]
yup, you are right, 
but in my case as i want to run test for different variants simultaneously, it won't work. It will pickup the device that you mentioned in build.gradle file for both variants, and hence will run them one after another.
Correct me if I'm wrong.
```
./gradlew spoonProjectADebugAndroidTest -PdeviceId=firstDeviceId
./gradlew spoonProjectBDebugAndroidTest -PdeviceId=secondDeviceId
```
In this way, these are two different process running test on two device simultaneously.

**Comment by roman-mazur** [comment]
What I'm talking about is that you will achieve the same result with the following lines in your build.gradle, without the plugin modification:
```groovy
spoon {
  if (project.hasProperty('deviceId')) {
    devices = [project.deviceId]
  }
}
```

**Comment by jainsahab** [comment]
yup, you are right.
Apologies, 
i am new to groovy so didn't know this way to assign the variable `devices`.
I should've seen this [example](https://github.com/stanfy/spoon-gradle-plugin#test-sharding) .

Thank you for your time.

**Pull request closed without merging**
